spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            clientId: 6umf0bm445vg0p2rnv99lnvcti
            clientSecret: 6ke0aojttir8uqqb1gmc8bul1reh67s4t4oj2ugha4qh74q1qup
            scope: openid
            redirect-uri: http://localhost:8080/login/oauth2/code/cognito
            clientName: arinsapp
        provider:
          cognito:
            issuerUri: https://cognito-idp.eu-north-1.amazonaws.com/eu-north-1_oUHHULFJL
            user-name-attribute: username


cognito:
  userPoolId: eu-north-1_oUHHULFJL
